[package]
name = "nes_emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = { version = "0.13.1", features = ["macros"] }

[dev-dependencies]
rand = { version = "=0.7.3"}
sdl2 = { version = "0.34.0"}